project_news/news/urls.py
from django.contrib import admin
from django.urls import path
from news.views import *
from .views import add_news,NewsDetailView,NewsListView


app_name = 'news'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news_list/', NewsListView.as_view(), name='news_list'),
    path('news_detail/<int:pk>', NewsDetailView.as_view(), name='news_detail'),
    path('add/', add_news, name='add_news'),
]

project_news/project_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls'))
]

project_news/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum



class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique = True)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    ARTICLE = 'AR'
    NEWS = 'NW'
    CATEGORY_CHOICES = (
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:124] + '...'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.commentPost.author.authorUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

class News(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

project_news/news/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'text', 'author']

project_news/news/views.py
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import News
from django.shortcuts import render, get_object_or_404, redirect
from .forms import NewsForm

class NewsListView(ListView):
    model = News
    template_name = 'news_list.html'
    context_object_name = 'news_list'

    def news_list(request):
        news = News.objects.order_by('-created_at')
        return render(request, 'news_list.html', {'news': news})

class NewsDetailView(DetailView):
    model = News
    template_name = 'news_detail.html'
    context_object_name = 'news'

    def news_detail(request, pk):
        news = get_object_or_404(News, pk=pk)
        return render(request, 'news_detail.html', {'news': news})


def add_news(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('news_list')
    else:
        form = NewsForm()
    return render(request, 'add_news.html', {'form': form})

project_news/news/templates/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавление новостей</title>
</head>
<body>
    <h1>Add News</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
</body>
</html>

project_news/news/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
    Project_news
{% endblock title %}
</title>
    {% load static %}
</head>
<body>
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Главная</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Новости</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Вход</button>
       <button type="button" class="btn btn-warning">Регистрация</button>
     </div>
   </div>
 </div>
</header>
<div class="container">
 {% block content %}
    {{ flatpage.content }}
 {% endblock content %}
</div>

</body>
</html>

project_news/news/templates/news_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
</head>
<body>
<!-- news_detail.html -->
{% extends 'default.html' %}

{% block content %}
  <h1>Детали новости</h1>

  <h2>{{ news.title }}</h2>
  <p>Дата публикации: {{ news.created_at|date:"d.m.Y" }}</p>
  <p>{{ news.text }}</p>
{% endblock %}

</body>
</html>

project_news/news/templates/news_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Новости</title>
</head>
<body>
<!-- news_list.html -->
{% extends 'default.html' %}

{% block content %}
  <h1>Список новостей</h1>
<a href="{% url 'news:news_list' %}">Список новостей</a>
<p>Количество новостей: {{ news|length }}</p>

{% for item in news %}
    <h2>{{ item.title }}</h2>
    <p>Дата публикации: {{ item.created_at|date:"d.m.Y" }}</p>
    <p>{{ item.text|truncatewords:20 }}</p>
    <a href="/news/{{ item.id }}">Подробнее</a>
{% empty %}
    <p>Нет доступных новостей.</p>
{% endfor %}
{% endblock %}
</body>
</html>

project_news/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
    Project_news
{% endblock title %}
</title>
    {% load static %}
</head>
<body>
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Главная</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Новости</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Вход</button>
       <button type="button" class="btn btn-warning">Регистрация</button>
     </div>
   </div>
 </div>
</header>
<div class="container">
 {% block content %}
    {{ flatpage.content }}
 {% endblock content %}
</div>

</body>
</html>

project_news/templates/news_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- news_detail.html -->
{% extends 'default.html' %}

{% block content %}
  <h1>Детали новости</h1>

  <h1>{{ news.title }}</h1>
<p>Дата публикации: {{ news.created_at|date:"d.m.Y" }}</p>
<p>{{ news.text }}</p>
{% endblock %}

</body>
</html>

project_news/templates/news_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- news_list.html -->
{% extends 'default.html' %}

{% block content %}
  <h1>Список новостей</h1>

  <p>Количество новостей: {{ news|length }}</p>

  {% for item in news %}
    <h2>{{ item.title }}</h2>
    <p>Дата публикации: {{ item.created_at|date:"d.m.Y" }}</p>
    <p>{{ item.text|truncatewords:20 }}</p>
    <hr>
  {% endfor %}
{% endblock %}

</body>
</html>